### ISSUE TITLE
Url not loading create below error

### ISSUE THREAD

**Issue by Office-Murtaza** [skydoves/landscapist#488]
implementation("com.github.skydoves:landscapist-glide:2.3.3")
    implementation("com.github.skydoves:landscapist-animation:2.3.3")
    implementation("com.github.skydoves:landscapist-palette:2.3.3")
    implementation("com.github.skydoves:landscapist-placeholder:2.3.3")
 
Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
2024-05-30 17:18:18.684  5971-6207  System.out              com...generator.aiart.texttoimageai  I  (HTTPLog)-Static: isSBSettingEnabled false
2024-05-30 17:18:18.684  5971-6207  System.out              com...generator.aiart.texttoimageai  I  (HTTPLog)-Static: isSBSettingEnabled false
2024-05-30 17:18:19.518  5971-5971  Glide                   com...generator.aiart.texttoimageai  W  Load failed for [https://pub-3626123a908346a7a8be8d9295f44e26.r2.dev/generations/0-76ccacf7-83c3-4534-a9fa-30c467520da6.png] with dimensions [720x613]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                                                    There was 1 root cause:
                                                                                                    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
                                                                                                     call GlideException#logRootCauses(String) for more detail
                                                                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                                                                    There was 1 root cause:
                                                                                                    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
                                                                                                     call GlideException#logRootCauses(String) for more detail
                                                                                                        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                                                    There was 1 root cause:
                                                                                                    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
                                                                                                     call GlideException#logRootCauses(String) for more detail
                                                                                                          Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 404
2024-05-30 17:18:19.520  5971-5971  Glide                   com...generator.aiart.texttoimageai  I  Root cause (1 of 1)
                                                                                                    com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 404
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
                                                                                                    	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)
                                                                                                    Caused by: java.io.FileNotFoundException: https://pub-3626123a908346a7a8be8d9295f44e26.r2.dev/generations/0-76ccacf7-83c3-4534-a9fa-30c467520da6.png
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95)
                                                                                                    	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) 
                                                                                                    	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95) 
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383) 

the url of image is not showing i have also add url

**Comment by skydoves** [comment]
I think you can find a solution from here:

https://stackoverflow.com/questions/49901629/glide-showing-error-failed-to-find-generatedappglidemodule
