### ISSUE TITLE
CoilImage does not load the image when used within GoogleMap's MarkerComposable

### ISSUE THREAD

**Issue by ArleyPereira** [skydoves/landscapist#527]
CoilImage does not load the image when used within GoogleMap's MarkerComposable.

CoilImage works outside of GoogleMap's, but does not work inside of MarkerComposable.

Import: com.github.skydoves:landscapist-coil3
Version: 2.3.3

There seems to be a problem in Compose Maps, but I'm not sure.
https://github.com/googlemaps/android-maps-compose/issues/542

agp = "8.3.2"
kotlin = "2.0.0"
composeBom = "2024.06.00"
compose-maps = "6.1.1"

```
Column(
        modifier = Modifier
            .fillMaxSize(),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        if(state.sharedList.isNotEmpty()){
            CoilImage(
                imageModel = { state.sharedList[0].sharer?.avatar },
                modifier = Modifier
                    .size(64.dp)
                    .clip(shape = CircleShape)
                    .border(BorderStroke(2.dp, Color.Black), shape = CircleShape),
                imageOptions = ImageOptions(contentScale = ContentScale.Crop),
                previewPlaceholder = null,
                loading = {},
                failure = {}
            )
        }

        GoogleMap(
            modifier = Modifier.fillMaxSize(),
            onMapLoaded = { isMapLoaded = true },
            cameraPositionState = cameraPositionState,
            uiSettings = uiSettings,
            content = {
                state.sharedList.forEach { shared ->
                    MarkerComposable(
                        state = MarkerState(
                            position = LatLng(
                                shared.sharer?.location?.latitude ?: 0.0,
                                shared.sharer?.location?.longitude ?: 0.0
                            )
                        ),
                        content = {
                            CoilImage(
                                imageModel = { state.sharedList[0].sharer?.avatar },
                                modifier = Modifier
                                    .size(64.dp)
                                    .clip(shape = CircleShape)
                                    .border(BorderStroke(2.dp, Color.Black), shape = CircleShape),
                                imageOptions = ImageOptions(contentScale = ContentScale.Crop),
                                previewPlaceholder = null,
                                loading = {},
                                failure = {}
                            )
                        }
                    )
                }
            }
        )
    }
```

![image](https://github.com/user-attachments/assets/fb8dfd48-88ea-4987-a0a8-3e6632d39b99)

**Comment by skydoves** [comment]
Hmm, that's weird. I've used the `GoogleMap` with `CoilImage` very well with the `Clustering` composable function like the image below:

![image](https://github.com/user-attachments/assets/6ffced1f-f6e9-4bc1-aed7-1e6d4aa4c6c3)

**Comment by skydoves** [comment]
Have you ever logged the URL destination of your avatar?

**Comment by ArleyPereira** [comment]
Yes. state.sharedList[0].sharer?.avatar has the value:
https://bk-find.s3.us-east-2.amazonaws.com/storage/users/2024/07/b8972ee47291321729074f91.png

From what I read in the problem in Compose maps, it was solved with Clustering, but it doesn't work without Clustering. I don't know exactly what Clustering would be, but do you have an example of code that I can use?

**Comment by skydoves** [comment]
@ArleyPereira Have you tried with the version `4.2.0` or `6.1.1`?

**Comment by ArleyPereira** [comment]
@skydoves I'm currently using version 6.1.1 and it doesn't work. Today I tested version 4.2.0 and it didn't work either.

**Comment by skydoves** [comment]
Hey @ArleyPereira, let me check out those versions. But out of my curiosity, why you don't use `Cluster` composable?

**Comment by ArleyPereira** [comment]
@skydoves From what I researched, Clustering is used to group markers according to zoom. My app doesn't have this grouping requirement have group markers.

**Comment by skydoves** [comment]
Hey @ArleyPereira, I concluded this issue completely came from a Google Map Compose issue, not from this library. The Google Map Compose creates its own bitmap description from the Composable, and it also uses a dedicated rendering node + `Applier` for loading each marker. I believe they wanted to optimize the recomposition performance of the markers and didn't allow the tracking of the changes of the marker (so if the network image composable functions are updated after the drawing is completed, eventually, it won't be rendered). I was trying to update the content of the `MarkerComposable` and it shows the error below:

```
   java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
                                                                                                    	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:726)
                                                                                                    	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
                                                                                                    	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
                                                                                                    	at android.graphics.Canvas.drawBitmap(Canvas.java:1604)
                                                                                                    	at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:275)
                                                                                                    	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-AZ2fEMs(CanvasDrawScope.kt:260)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-AZ2fEMs(Unknown Source:24)
                                                                                                    	at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-AZ2fEMs$default(DrawScope.kt:587)
                                                                                                    	at androidx.compose.ui.graphics.painter.BitmapPainter.onDraw(BitmapPainter.kt:93)
                                                                                                    	at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
                                                                                                    	at androidx.compose.ui.draw.PainterNode.draw(PainterModifier.kt:343)
```

I think you need to keep watching the link related to the Compose Map issues. Thanks!
